let dogs = ["Unknown/Mixed",
"Affenpinscher",
"Aidi",
"Airedale Terrier",
"Akbash Dog",
"Akita Inu",
"Alano Espanol",
"Alapaha Blue Blood Bulldog",
"Alaskan Klee Kai",
"Alaskan Malamute",
"Alpine Dachsbracke",
"Alpine Spaniel",
"American Akita",
"American Alsatian",
"American Bulldog",
"American Bully",
"American Cocker Spaniel",
"American Eskimo Dog",
"American Foxhound",
"American Hairless Terrier",
"American Mastiff",
"American Pit Bull Terrier",
"American Staffordshire Terrier",
"American Water Spaniel",
"Anatolian Shepherd Dog",
"Anglo-Francais de Petite Venerie",
"Antebellum Bulldog",
"Appenzeller Sennenhund",
"Ariegeois",
"Ariege Pointer",
"Armant",
"Armenian Gampr dog",
"Artois Hound",
"Aussiedoodle",
"Australian Bulldog",
"Australian Cattle Dog",
"Australian Kelpie",
"Australian Shepherd",
"Australian Silky Terrier",
"Australian Stumpy Tail Cattle Dog",
"Australian Terrier",
"Austrian Black and Tan Hound",
"Austrian Pinscher",
"Azawakh",
"Bakharwal Dog",
"Barbet",
"Basenji",
"Basque Shepherd Dog",
"Basset Artesien Normand",
"Basset Bleu de Gascogne",
"Basset Fauve de Bretagne",
"Basset Hound",
"Bavarian Mountain Hound",
"Beagle",
"Beagle-Harrier",
"Bearded Collie",
"Beauceron",
"Bedlington Terrier",
"Belgian Shepherd Dog (Groenendael)",
"Belgian Shepherd Dog (Laekenois)",
"Belgian Shepherd Dog (Malinois)",
"Belgian Shepherd Dog (Tervuren)",
"Bergamasco Shepherd",
"Berger Blanc Suisse",
"Berger Picard",
"Bernedoodle",
"Berner Laufhund",
"Bernese Mountain Dog",
"Bichon Frise",
"Biewer Terrier",
"Billy",
"Bisben",
"Black and Tan Coonhound",
"Black and Tan Virginia Foxhound",
"Blackmouth Cur",
"Black Norwegian Elkhound",
"Black Russian Terrier",
"Bloodhound",
"Blue Lacy",
"Blue Paul Terrier",
"Blue Picardy Spaniel",
"Bluetick Coonhound",
"Boerboel",
"Bohemian Shepherd",
"Bolognese",
"Border Collie",
"Border Terrier",
"Borzoi",
"Bosnian Coarse-haired Hound",
"Boston Terrier",
"Bouvier des Ardennes",
"Bouvier des Flandres",
"Boxer",
"Boykin Spaniel",
"Bracco Italiano",
"Braque d'Auvergne",
"Braque du Bourbonnais",
"Braque du Puy",
"Braque Francais",
"Braque Saint-Germain",
"Brazilian Terrier",
"Briard",
"Briquet Griffon Vendeen",
"Brittany",
"Broholmer",
"Bruno Jura Hound",
"Bucovina Shepherd Dog",
"Bull and Terrier",
"Bull Arab",
"Bulldog Campeiro",
"Bullenbeisser",
"Bullmastiff",
"Bullpug",
"Bull Terrier",
"Bull Terrier (Miniature)",
"Bully Kutta",
"Cairn Terrier",
"Canaan Dog",
"Canadian Eskimo Dog",
"Canadian Pointer",
"Cane Corso",
"Cao da Serra de Aires",
"Cao de Castro Laboreiro",
"Cao Fila de Sao Miguel",
"Cardigan Welsh Corgi",
"Carolina Dog",
"Carpathian Shepherd Dog",
"Catahoula Leopard Dog",
"Catalan Sheepdog",
"Caucasian Shepherd Dog",
"Cavachon",
"Cavador",
"Cavalier King Charles Spaniel",
"Cavapoo",
"Cavipoo",
"Central Asian Shepherd Dog",
"Cesky Fousek",
"Cesky Terrier",
"Cheegle",
"Chesapeake Bay Retriever",
"Chien Francais Blanc et Noir",
"Chien Francais Blanc et Orange",
"Chien Francais Tricolore",
"Chien-gris",
"Chihuahua",
"Chilean Fox Terrier",
"Chinese Chongqing Dog",
"Chinese Crested Dog",
"Chinese Imperial Dog",
"Chinook",
"Chippiparai",
"Chiweenie",
"Chow Chow",
"Cierny Sery",
"Cimarron Uruguayo",
"Cirneco dell'Etna",
"Clumber Spaniel",
"Cockapoo",
"Combai",
"Cordoba Fighting Dog",
"Corgidor",
"Coton de Tulear",
"Cretan Hound",
"Croatian Sheepdog",
"Cumberland Sheepdog",
"Curly Coated Retriever",
"Cursinu",
"Czechoslovakian Wolfdog",
"Dachshund",
"Dalmatian",
"Dandie Dinmont Terrier",
"Danish Swedish Farmdog",
"Deutsche Bracke",
"Doberman Pinscher",
"Dogo Argentino",
"Dogo Cubano",
"Dogo Guatemalteco",
"Dogo Sardesco",
"Dogue de Bordeaux",
"Double doodle",
"Drentse Patrijshond",
"Drever",
"Dunker",
"Dutch Shepherd Dog",
"Dutch Smoushond",
"East-European Shepherd",
"East Siberian Laika",
"Elo",
"English Bulldog",
"English Cocker Spaniel",
"English Coonhound",
"English Foxhound",
"English Mastiff",
"English Setter",
"English Shepherd",
"English Springer Spaniel",
"English Toy Terrier (Black Tan)",
"English Water Spaniel",
"English White Terrier",
"Entlebucher Mountain Dog",
"Entlebucher Sennenhund",
"Estonian Hound",
"Estrela Mountain Dog",
"Eurasier",
"Field Spaniel",
"Fila Brasileiro",
"Finnish Hound",
"Finnish Lapphund",
"Finnish Spitz",
"Flat-Coated Retriever",
"Formosan Mountain Dog",
"Fox Terrier (Smooth)",
"French Brittany",
"French Bulldog",
"French Spaniel",
"Galgo Espanol",
"Gascon Saintongeois",
"German Longhaired Pointer",
"German Pinscher",
"German Shepherd Dog",
"German Shorthaired Pointer",
"German Spaniel",
"German Spitz",
"German Wirehaired Pointer",
"Giant Schnauzer",
"Glen of Imaal Terrier",
"Goldador",
"Golden Retriever",
"Gordon Setter",
"Grand Anglo-Francais Blanc et Noir",
"Grand Anglo-Francais Blanc et Orange",
"Grand Anglo-Francais Tricolore",
"Grand Basset Griffon Vendeen",
"Grand Bleu de Gascogne",
"Grand Griffon Vendeen",
"Gran Mastin de Borinquen",
"Great Dane",
"Greater Swiss Mountain Dog",
"Great Pyrenees",
"Greek Harehound",
"Greenland Dog",
"Greyhound",
"Griffon Bleu de Gascogne",
"Griffon Bruxellois",
"Griffon Fauve de Bretagne",
"Griffon Nivernais",
"Gull Dong",
"Gull Terr",
"Hamiltonstovare",
"Hanover Hound",
"Hare Indian Dog",
"Harrier",
"Havanese",
"Hawaiian Poi Dog",
"Himalayan Sheepdog",
"Hokkaido",
"Hortaya borzaya",
"Hovawart",
"Hungarian Hound",
"Hygenhund",
"Ibizan Hound",
"Icelandic Sheepdog",
"Indian Spitz",
"Irish Red and White Setter",
"Irish Setter",
"Irish Terrier",
"Irish Water Spaniel",
"Irish Wolfhound",
"Istrian Coarse-haired Hound",
"Istrian Shorthaired Hound",
"Italian Greyhound",
"Jack Russell Terrier",
"Jagdterrier",
"Jamthund",
"Japanese Chin",
"Japanese Spitz",
"Japanese Terrier",
"Jonangi",
"Kaikadi",
"Kai Ken",
"Kangal Dog",
"Kanni",
"Karakachan Dog",
"Karelian Bear Dog",
"Karst Shepherd",
"Keeshond",
"Kerry Beagle",
"Kerry Blue Terrier",
"King Charles Spaniel",
"King Shepherd",
"Kintamani",
"Kishu",
"Komondor",
"Kooikerhondje",
"Koolie",
"Korean Jindo Dog",
"Korean Mastiff",
"Kromfohrlander",
"Kunming Wolfdog",
"Kuri",
"Kuvasz",
"Kyi-Leo",
"Labradoodle",
"Labrador Husky",
"Labrador Retriever",
"Labsky",
"Lagotto Romagnolo",
"Lakeland Terrier",
"Lancashire Heeler",
"Landseer",
"Lapponian Herder",
"Large Munsterlander",
"Leonberger",
"Lhasa Apso",
"Lithuanian Hound",
"Longhaired Whippet",
"Lowchen",
"Magyar agar",
"Malador",
"Maltese",
"Maltipoo",
"Manchester Terrier",
"Maremma Sheepdog",
"McNab",
"Mexican Hairless Dog",
"Mi-Ki",
"Miniature Australian Shepherd",
"Miniature Fox Terrier",
"Miniature Pinscher",
"Miniature Poodle",
"Miniature Schnauzer",
"Mini aussie",
"Mini Goldendoodle",
"Mioritic",
"Molossus",
"Montenegrin Mountain Hound",
"Morkie",
"Moscow Watchdog",
"Moscow Water Dog",
"Mountain Cur",
"Mountain Feist",
"Mountain View Cur",
"Mucuchies",
"Mudhol Hound",
"Mudi",
"Murray River Curly Coated Retriever",
"Mutt",
"Neapolitan Mastiff",
"Newfoundland",
"New Zealand Huntaway",
"Norfolk Spaniel",
"Norfolk Terrier",
"Norrbottenspets",
"North Country Beagle",
"Northern Inuit Dog",
"Norwegian Buhund",
"Norwegian Elkhound",
"Norwegian Lundehund",
"Norwich Terrier",
"Nova Scotia Duck Tolling Retriever",
"Old Croatian Sighthound",
"Old Danish Pointer",
"Olde English Bulldogge",
"Old English Bulldog",
"Old English Sheepdog",
"Old English Terrier",
"Old German Shepherd Dog",
"Old Time Farm Shepherd",
"Otterhound",
"Pachon Navarro",
"Paisley Terrier",
"Papillon",
"Papshund",
"Parson Russell Terrier",
"Patterdale Terrier",
"Peekpoo",
"Pekingese",
"Pembroke Welsh Corgi",
"Perro de Presa Canario",
"Perro de Presa Mallorquin",
"Peruvian Hairless Dog",
"Petit Basset Griffon Vendeen",
"Petit Bleu de Gascogne",
"Phalene",
"Pharaoh Hound",
"Phu Quoc ridgeback dog",
"Picardy Spaniel",
"Pitbull",
"Pitsky",
"Plott Hound",
"Podenco Canario",
"Pointer",
"Polish Greyhound",
"Polish Hound",
"Polish Hunting Dog",
"Polish Lowland Sheepdog",
"Polish Tatra Sheepdog",
"Pomchi",
"Pomeranian",
"Pomsky",
"Pont-Audemer Spaniel",
"Porcelaine",
"Portuguese Podengo",
"Portuguese Pointer",
"Portuguese Water Dog",
"Posavaz Hound",
"Prazsky Krysarik",
"Pudelpointer",
"Pug",
"Puggle",
"Puli",
"Pumi",
"Pungsan Dog",
"Pyrenean Mastiff",
"Pyrenean Shepherd",
"Queensland Blue Heeler",
"Queensland Heelers",
"Rafeiro do Alentejo",
"Rajapalayam",
"Rampur Greyhound",
"Rastreador Brasileiro",
"Ratonero Bodeguero Andaluz",
"Rat Terrier",
"Redbone Coonhound",
"Rhodesian Ridgeback",
"Rottweiler",
"Rough Collie",
"Russell Terrier",
"Russian Spaniel",
"Russian Tsvetnaya Bolonka",
"Russkiy Toy",
"Russo-European Laika",
"Saarlooswolfhond",
"Sabueso Espanol",
"Saint-Usuge Spaniel",
"Sakhalin Husky",
"Saluki",
"Samoyed",
"Sapsali",
"Sarplaninac",
"Schapendoes",
"Schillerstovare",
"Schipperke",
"Schnoodle",
"Schweizerischer Niederlaufhund",
"Schweizer Laufhund",
"Scotch Collie",
"Scottish Deerhound",
"Scottish Terrier",
"Sealyham Terrier",
"Segugio Italiano",
"Seppala Siberian Sleddog",
"Serbian Hound",
"Serbian Tricolour Hound",
"Shar Pei",
"Shetland Sheepdog",
"Shiba Inu",
"Shih Tzu",
"Shikoku",
"Shiloh Shepherd Dog",
"Siberian Husky",
"Silken Windhound",
"Sinhala Hound",
"Skye Terrier",
"Sloughi",
"Slovak Cuvac",
"Slovakian Rough-haired Pointer",
"Slovensky kopov",
"Smalandsstovare",
"Small Greek Domestic Dog",
"Small Munsterlander",
"Smooth Collie",
"Soft-Coated Wheaten Terrier",
"Southern Hound",
"South Russian Ovcharka",
"Spanish Mastiff",
"Spanish Water Dog",
"Spinone Italiano",
"Sporting Lucas Terrier",
"Stabyhoun",
"Staffordshire Bull Terrier",
"Standard Poodle",
"Standard Schnauzer",
"St. Bernard",
"Stephens Cur",
"St. John's Water Dog",
"Styrian Coarse-haired Hound",
"Sussex Spaniel",
"Swedish Lapphund",
"Swedish Vallhund",
"Tahltan Bear Dog",
"Taigan",
"Talbot",
"Tamaskan Dog",
"Teddy Roosevelt Terrier",
"Telomian",
"Tenterfield Terrier",
"Thai Bangkaew Dog",
"Thai Ridgeback",
"Tibetan Mastiff",
"Tibetan Spaniel",
"Tibetan Terrier",
"Tornjak",
"Tosa",
"Toy Bulldog",
"Toy Fox Terrier",
"Toy Manchester Terrier",
"Toy Poodle",
"Toy Trawler Spaniel",
"Transylvanian Hound",
"Treeing Cur",
"Treeing Tennessee Brindle",
"Treeing Walker Coonhound",
"Trigg Hound",
"Tweed Water Spaniel",
"Tyrolean Hound",
"Unknown mix-breed",
"Utonagan",
"Vizsla",
"Volpino Italiano",
"Weimaraner",
"Welsh Sheepdog",
"Welsh Springer Spaniel",
"Welsh Terrier",
"West Highland White Terrier",
"Westphalian Dachsbracke",
"West Siberian Laika",
"Wetterhoun",
"Whippet",
"White English Bulldog",
"White Shepherd Dog",
"Wire Fox Terrier",
"Wirehaired Pointing Griffon",
"Wirehaired Vizsla",
"Xoloitzcuintli",
"Yoranian",
"Yorkiepoo",
"Yorkshire Terrier",
"Yorktese"];

dogs.forEach(function (value) {
    console.log("{ value:" + value + ", label:" + value +  "}");
  }); 